const REGISTER = 'REGISTER'
//const REGISTER_PASS = 'REGISTER_PASS'
//const REGISTER_ERROR = 'REGISTER_ERROR'
const CLEAR_ERRORS = 'CLEAR_ERRORS'
const LOGIN = 'LOGIN'
const LOGIN_PASS = 'LOGIN_PASS'
const USER_ERROR = 'USER_ERROR'
const SIGNUP_PASS = 'SIGNUP_PASS'
const OFF_SHOW_REGTOAST = 'OFF_SHOW_REGTOAST'
const LOGOUT = 'LOGOUT'
const SET_STOCK_ERROR = 'SET_STOCK_ERROR'
const DEL_STOCK_ERROR = 'DEL_STOCK_ERROR'
export {
  REGISTER,
  LOGIN,
  LOGIN_PASS,
  USER_ERROR,
  CLEAR_ERRORS,
  SIGNUP_PASS,
  OFF_SHOW_REGTOAST,
  LOGOUT,
  SET_STOCK_ERROR,
  DEL_STOCK_ERROR,
}
