const REGISTER = 'REGISTER'
//const REGISTER_PASS = 'REGISTER_PASS'
//const REGISTER_ERROR = 'REGISTER_ERROR'
const CLEAR_ERRORS = 'CLEAR_ERRORS'
const LOGIN = 'LOGIN'
const LOGIN_PASS = 'LOGIN_PASS'
const USER_ERROR = 'USER_ERROR'

export { REGISTER, LOGIN, LOGIN_PASS, USER_ERROR, CLEAR_ERRORS }
